version: "3.7"

services:
  sqlServer:
    container_name: sqlserver
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=yourStrong(!)Password"
      - "ACCEPT_EULA=Y"
    ports:
      - 1433:1433
    networks:
      - shared
  dictionary:
    container_name: dictionary
    build: .
    ports:
      - "63823:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "docker"
    depends_on:
      - sqlServer
    restart: on-failure
    networks:
      - shared
networks:
  shared:
    driver: bridge
  