version: "3.7"

services:
  dictionary:
    container_name: dictionary
    build: .
    ports:
      - "63823:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "docker"
    depends_on:
      - sqlServer
    restart: always
    networks:
      - shared
networks:
  shared:
    driver: bridge
  